Feature/updating indeed scraper (#166)
PaulMcInnis/JobFunnel pull request #170
Opened 2024-09-13 02:10 UTC by sammytheindi

## Description

Merging fixed indeed scraper into master branch. For more information, see #166 
Additional changes include updates to formatting, adding black and prettier configuration files, and performing minor updates to the repo (versioning, updating modules, etc.). 

Biggest point of discussion is whether we want to keep the current method of scraping each individual job page, or scraping the job list with description summaries. The latter (default implementation in this PR), is **much** faster, though will result in less information in the description. It is possible to manually switch back, but do we want to keep it as the default implementation?

## Context of change

- [x] Software (software that runs on the PC)
- [ ] Library (library that runs on the PC)
- [ ] Tool (tool that assists coding development)
- [ ] Other

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Same tests as in #166 

## Checklist:

- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-09-13 16:48 UTC, PaulMcInnis requested changes
lets put back the markdown + demo file but other than this i'm approving it

2024-09-14 02:14 UTC, sammytheindi commented on jobfunnel/resources/user_agent_list_mobile.txt
> +Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Indeed App 225.0
We can actually get rid of the first one, only had it in as a reference. I assume that's what you mean?

2024-09-14 21:35 UTC, PaulMcInnis requested changes
wow makes me so happy to see this working again :) 

a few things

1. we should update readme to say that 3.11 is required at least
2. we need to add `user_agent_mobile.txt` to the `MANIFEST.in` file so that it is properly packaged when you install/run using `pip install .` and the `funnel load -s...` path

2024-09-17 11:43 UTC, sammytheindi commented
Thanks @PaulMcInnis, we should be good to go! 

As I was updating, I was wondering why this project still uses `setup.py`, instead of the newer standard of `pyproject.toml` + `setup.cfg` ([PEP-518](https://peps.python.org/pep-0518/)). 

I will open a new issue on this as I believe we should probably switch while the project is still small, but would love to hear if there are any reasons not to.

2024-09-17 15:06 UTC, PaulMcInnis commented
> Thanks @PaulMcInnis, we should be good to go!
> 
> As I was updating, I was wondering why this project still uses `setup.py`, instead of the newer standard of `pyproject.toml` + `setup.cfg` ([PEP-518](https://peps.python.org/pep-0518/)).


Hey there,  no reason other than age really - this is an old project and it needs some love

2024-09-17 15:07 UTC, merged